language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script: "true"
deploy:
  provider: gae
  keyfile: gae.json
  project: whunter
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - npm test
before_install:
  - openssl aes-256-cbc -K $encrypted_6e8fb3912adb_key -iv $encrypted_6e8fb3912adb_iv
    -in gae.json.enc -out gae.json -d
